api = "0.7"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/yarn-start"
  id = "paketo-buildpacks/yarn-start"
  name = "Paketo Buildpack for Yarn Start"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/yarn-start/blob/main/LICENSE"

[metadata]
  include-files = [
    "buildpack.toml",
    "linux/amd64/bin/build",
    "linux/amd64/bin/detect",
    "linux/amd64/bin/run",
    "linux/arm64/bin/build",
    "linux/arm64/bin/detect",
    "linux/arm64/bin/run",
  ]

  pre-package = "./scripts/build.sh --target linux/amd64 --target linux/arm64"

[[stacks]]
  id = "*"

[[targets]]
  os = "linux"
  arch = "amd64"

[[targets]]
  os = "linux"
  arch = "arm64"